name: Deploy and Restart Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} 'echo "SSH connection successful"'

    # - name: Copy files to server
    #   run: scp -o StrictHostKeyChecking=no -r ./* username@${{ secrets.SERVER_IP }}:/path/to/your/app

    # - name: Restart server
    #   run: |
    #     ssh -o StrictHostKeyChecking=no username@${{ secrets.SERVER_IP }} << 'EOF'
    #     cd /path/to/your/app
    #     docker-compose down
    #     docker-compose up --build -d
    #     EOF
