name: Deploy and Restart Server

on:
  push:
    branches:
      - main  # или другая ветка, в которой хотите запускать действие

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # - name: Setup SSH
    #   run: |
    #     mkdir -p ~/.ssh/
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
    #     chmod 600 ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa.pub
    #     ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/authorized_keys

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key:${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        scp -r ./* root@${{ secrets.SERVER_IP }}:/home/ubuntu/action_test
# git pull

    - name: Restart server
      run: |
        ssh root@${{ secrets.SERVER_IP }}
        cd /home/ubuntu/action_test
        docker-compose down
        docker-compose up --build -d
